enum PostsActions {
    GET_FEED_REQUEST = "GET_FEED_REQUEST",
    GET_FEED_SUCCESS = "GET_FEED_SUCCESS",
    GET_FEED_ERROR = "GET_FEED_ERROR",

    ADD_POST_REQUEST = "ADD_POST_REQUEST",
    ADD_POST_SUCCESS = "ADD_POST_SUCCESS",
    ADD_POST_ERROR = "ADD_POST_ERROR",
}

export default PostsActions;