enum AuthActions {
    AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST",
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR",

    AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST",
    AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
    AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR",
    
    AUTH_REFRESH_TOKEN_REQUEST = "AUTH_REFRESG_TOKEN_REQUEST",
    AUTH_REFRESH_TOKEN_SUCCESS = "AUTH_REFRESH_TOKEN_SUCCESS",
    AUTH_REFRESH_TOKEN_ERROR = "AUTH_REFRESH_TOKEN_ERROR",
}

export default AuthActions