enum AuthActions {
    AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST",
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE",
    AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST",
    AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
    AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE",
    AUTH_REFRESH_TOKEN_REQUEST = "AUTH_REFRESG_TOKEN_REQUEST",
    AUTH_REFRESH_TOKEN_SUCCESS = "AUTH_REFRESH_TOKEN_SUCCESS",
    AUTH_REFRESH_TOKEN_FAILURE = "AUTH_REFRESH_TOKEN_FAILURE",
}

export default AuthActions