enum AuthActions {
    AUTH_LOGIN = "AUTH_LOGIN",
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE",
    AUTH_LOGOUT = "AUTH_LOGOUT",
    AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",
    AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN",
}

export default AuthActions