enum UserActions {
    GET_PROFILE = "USER_GET_PROFILE",
    UPDATE_PROFILE = "USER_UPDATE_PROFILE",
    UPDATE_AVATAR = "USER_UPDATE_AVATAR",
    DELETE_AVATAR = "USER_DELETE_AVATAR",
    GET_FOLLOW_SUGGESTIONS = "USER_GET_FOLLOW_SUGGESTIONS",
    GET_FOLLOWING = "USER_GET_FOLLOWING",
    ADD_FOLLOWING = "USER_ADD_FOLLOWING",
    REMOVE_FOLLOWING = "USER_REMOVE_FOLLOWING",
    GET_NOTIFICATIONS = "USER_GET_NOTIFICATIONS",
    MARK_ALL_NOTIFICATIONS_AS_READ = "USER_MARK_ALL_NOTIFICATIONS_AS_READ",
    READ_NOTIFICATION = "USER_READ_NOTIFICATION",
    UNREAD_NOTIFICATION = "USER_UNREAD_NOTIFICATION",
}

export default UserActions