enum UserActions {
    GET_PROFILE = "USER_GET_PROFILE",
    UPDATE_PROFILE = "USER_UPDATE_PROFILE",
    UPDATE_AVATAR = "USER_UPDATE_AVATAR",
    DELETE_AVATAR = "USER_DELETE_AVATAR",
    GET_FOLLOW_SUGGESTIONS = "USER_GET_FOLLOW_SUGGESTIONS",
    GET_FOLLOWING = "USER_GET_FOLLOWING",
    ADD_FOLLOWING = "USER_ADD_FOLLOWING",
    DELETE_FOLLOWING = "USER_DELETE_FOLLOWING",
    GET_NOTIFICATIONS = "USER_GET_NOTIFICATIONS",
    UPDATE_ALL_NOTIFICATIONS_AS_READ = "USER_MARK_ALL_NOTIFICATIONS_AS_READ",
    UPDATE_NOTIFICATION_AS_READ = "USER_UPDATE_NOTIFICATION_AS_READ",
    UPDATE_NOTIFICATION_AS_UNREAD = "USER_UPDATE_NOTIFICATION_AS_UNREAD",
}

export default UserActions