enum UserActions {
    USER_REQUEST_ERROR = "USER_REQUEST_ERROR",
    USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS", 
    
    GET_PROFILE_REQUEST = "USER_GET_PROFILE_REQUEST",
    GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS",
    UPDATE_PROFILE = "USER_UPDATE_PROFILE",
    UPDATE_AVATAR = "USER_UPDATE_AVATAR",
    DELETE_AVATAR = "USER_DELETE_AVATAR",
    GET_FOLLOW_SUGGESTIONS = "USER_GET_FOLLOW_SUGGESTIONS",
    GET_FOLLOWING = "USER_GET_FOLLOWING",
    ADD_FOLLOWING = "USER_ADD_FOLLOWING",
    DELETE_FOLLOWING = "USER_DELETE_FOLLOWING",
    GET_NOTIFICATIONS_REQUEST = "USER_GET_NOTIFICATIONS_REQUEST",
    GET_NOTIFICATIONS_SUCCESS = "USER_GET_NOTIFICATIONS_SUCCESS",

    MARK_NOTIFICATION_AS_READ_REQUEST = "MARK_NOTIFICATION_AS_READ_REQUEST",
    MARK_NOTIFICATION_AS_READ_SUCCESS = "MARK_NOTIFICATION_AS_READ_SUCCESS",
    MARK_NOTIFICATION_AS_UNREAD_REQUEST = "MARK_NOTIFICATION_AS_UNREAD_REQUEST",
    MARK_NOTIFICATION_AS_UNREAD_SUCCESS = "MARK_NOTIFICATION_AS_UNREAD_SUCCESS",
}

export default UserActions