export enum ApiActions {
    API = "API",
    REQUEST_START = "REQUEST_START",
    REQUEST_END = "REQUEST_END",
    REQUEST_ERROR = "REQUEST_ERROR",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
}

export enum LoadingStatus {
    LOADING_USER = "LOADING_USER",
    LOADING_POSTS = "LOADING_POSTS",
    LOADING_NOTIFICATIONS = "LOADING_NOTIFICATIONS"
}